### ISSUE TITLE
Issue with testing nsrllookup

### ISSUE THREAD

**Issue by ghost** [cybagard/nsrllookup#1]
I'm using python 3.7 and tried to write the command 

```
sudo docker-compose -f docker-compose.build.yml up --build api-test &&  docker-compose -f docker-compose.build.yml rm -fsv
Building svr-test
```

and this is what I got 

![image](https://user-images.githubusercontent.com/77959925/106756118-fc7dae80-663f-11eb-8f1b-75c5c111c839.png)

**Comment by cybagard** [comment]
Hi, this is very likely an issue with your docker installation. Please use your favourite search engine to find a solution.
