### ISSUE TITLE
Why am I getting an error message when the URL works perfectly?

### ISSUE THREAD

**Issue by ghost** [cybagard/nsrllookup#2]
I tried to type http://MyHostName:5000/check/2706c2ee908f8a6269a96e1ecccdb5f9 on my browser and it worked perfectly.
So I tried to run test_ping.py but I got this error message.

```
Traceback (most recent call last):
  File "test_ping.py", line 7, in <module>
    from app import api
  File "/home/username/Desktop/nsrllookup-main/api/app.py", line 14, in <module>
    SERVER = os.environ['SERVER']
  File "/home/username/virtualenvironment/project_1/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'SERVER'
```
 Could you help me please to find the solution for this one?

Thnx

**Comment by cybagard** [comment]
You can run the test scripts with docker also (preferred). Just use the docker-compose.hub.test.yml docker-compose file. If you run the file directly, you are missing environment variables -> os.environ['SERVER']

**Comment by ghost** [comment]
Thank you

But not sure what to fill SERVER variable with?

**Comment by cybagard** [comment]
It is the hostname of the server (not the api)
